### ISSUE TITLE
Crash on Hydrogen Android [Apparently]

### ISSUE THREAD

**Issue by phoriah** [luau/UniversalSynSaveInstance#3]

**Comment by ActualMasterOogway** [comment]
> Should be fixed in [4559e23](https://github.com/luau/UniversalSynSaveInstance/commit/4559e2340ae28c27057220b5943709e99e66a51f). Needs to be tested & confirmed though.

Actually it still crashes, when i execute save instance roblox just closes. 

I looked into my workspace folder (/Android/data/com.roblox.client/files/Hydrogen/workspace) and i didnt find a ,rbxlx file there. i looked into /Android/data/com.roblox.client/files/ui and i a rbxlx file there that is 0 bytes big. This doesn't really have anything to do with USSI but i thought it was worth mentioning
