### ISSUE TITLE
Game crashing when saving huge place on Arceus X Neo [might be with other executors as well]

### ISSUE THREAD

**Issue by MuhXd** [luau/UniversalSynSaveInstance#5]
As the title saids, me and my friend were save decompling a game and it worked on a game ([fe2 2019](https://www.roblox.com/games/16501166943/FE2-2019) as a testing ground) and it works however we try a huge game (like [Liquid Breakout](https://www.roblox.com/games/741905805/UPDATE-Liquid-Breakout]) it crashes and it cause my phone background to crash as well. I would recommend a setting like Slower save instance, that adds waits to certain parts of the functions causing it to not freeze and crash as much

**Comment by MuhXd** [comment]
All in lb
Test results 
'*2': Crash after 1m~
'*3' Crash after 1:50s
'*4' Crash around the same as both
I'll do some more later (I tried recording them but it crashed it so it didn't work)

**Comment by MuhXd** [comment]
Tests 2-3 crashed with my wallpaper staying and 4 didn't keep my animated wallpaper

**Comment by MuhXd** [comment]
'*6' did the Same thing as "*4'

**Comment by MuhXd** [comment]
"*8' seemed to crash a bit faster then the others

**Comment by MuhXd** [comment]
All in lb
full message 
Test results
'*2': Crash after 1m~
'*3' Crash after 1:50s
'*4' Crash around the same as both
'*6' did the Same thing as "*4'
"*8' seemed to crash a bit faster then the others

**Comment by MuhXd** [comment]
https://github.com/luau/UniversalSynSaveInstance/assets/100521306/ebd168dc-b3e1-4595-97db-56f38fcc4ddd

Video using Phone link as it crashes

**Comment by MuhXd** [comment]
compressed as hell

**Comment by MuhXd** [comment]
It might be a ram as 
![Screenshot_20240331_144433_One UI Home](https://github.com/luau/UniversalSynSaveInstance/assets/100521306/624dad86-d494-4176-baac-d55918860b3c)
This is what is ment to be
https://github.com/luau/UniversalSynSaveInstance/assets/100521306/34e20912-66c8-41ee-a001-c6c8b70ab0d8

**Comment by MuhXd** [comment]
after the crash

**Comment by MuhXd** [comment]
also it didn't fix it, it did the same thing

**Comment by MuhXd** [comment]
crashes with wave as well

**Comment by MuhXd** [comment]
With wave it is a instant crash

**Comment by MuhXd** [comment]
@phoriah UPDATE: it doesn't work anymore on Arecus X Neo
![image](https://github.com/luau/UniversalSynSaveInstance/assets/100521306/9577f109-85a6-4c5f-ac19-84cde6713f78)

**Comment by MuhXd** [comment]
> > With wave it is a instant crash on high object places
> 
> Send game link

https://www.roblox.com/games/5797946894/Flood-Escape-But-Something-Aint-Right

**Comment by PatoFlamejanteTV** [comment]
i tried do download an heavy place (20MB<) on arceus x neo and worked fine. which android version are you using?

**Comment by MuhXd** [comment]
It seems to be fixed as it has stopped crashing
